
```{r}
library(tidyverse)
library(tidymodels)
library(modelr)
library(stringr)
```

```{r}
# Data for 2018-19
scores<-read.csv("raw_scores.csv")
vegas<-read.csv("vegas.csv")
teams<-read.csv("teams.csv")

## Cleaning ##

vegas$Team<-sub("Oklahoma City","OklahomaCity",vegas$Team)
vegas$Team<-sub("Golden State","GoldenState",vegas$Team)
vegas$Team<-sub("New York","NewYork",vegas$Team)
vegas$Team<-sub("New Orleans","NewOrleans",vegas$Team)
vegas$Team<-sub("San Antonio","SanAntonio",vegas$Team)
vegas$Team<-sub("L.A. Clippers","LAC",vegas$Team)
vegas$Team<-sub("L.A. Lakers","LAL",vegas$Team)

vegas$OppTeam<-sub("Oklahoma City","OklahomaCity",vegas$OppTeam)
vegas$OppTeam<-sub("Golden State","GoldenState",vegas$OppTeam)
vegas$OppTeam<-sub("New York","NewYork",vegas$OppTeam)
vegas$OppTeam<-sub("New Orleans","NewOrleans",vegas$OppTeam)
vegas$OppTeam<-sub("San Antonio","SanAntonio",vegas$OppTeam)
vegas$OppTeam<-sub("L.A. Clippers","LAC",vegas$OppTeam)
vegas$OppTeam<-sub("L.A. Lakers","LAL",vegas$OppTeam)

teams$Team<-str_replace_all(teams$Team,'\\*','')
teams$Team<-sub("Oklahoma City","OklahomaCity",teams$Team)
teams$Team<-sub("Golden State","GoldenState",teams$Team)
teams$Team<-sub("New York","NewYork",teams$Team)
teams$Team<-sub("New Orleans","NewOrleans",teams$Team)
teams$Team<-sub("San Antonio","SanAntonio",teams$Team)
teams$Team<-sub("Los Angeles Clippers","LAC",teams$Team)
teams$Team<-sub("Los Angeles","LAL",teams$Team)
teams$Team<-sub(" .*","",teams$Team)

vegas<-vegas[,c(3,6,14,30,31,49,50,58)]
data<-merge(vegas,teams,by="Team")

# save data as csv
write.csv(data,"data.csv")
```

